name: Auto Tweet Bot

on:
  schedule:
    # Every 30 minutes:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install openai tweepy

      - name: Run tweet bot
        env:
          OPENAI_API_KEY:    ${{ secrets.OPENAI_API_KEY }}
          TW_CONSUMER_KEY:   ${{ secrets.TW_CONSUMER_KEY }}
          TW_CONSUMER_SECRET:${{ secrets.TW_CONSUMER_SECRET }}
          TW_ACCESS_TOKEN:   ${{ secrets.TW_ACCESS_TOKEN }}
          TW_ACCESS_SECRET:  ${{ secrets.TW_ACCESS_SECRET }}
        run: python tweet_bot.py
